# Generated by Django 5.2.7 on 2026-08-05 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_customer'),
        ('reservations', '0004_reservation_arrived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('booking_reminder', 'Booking reminder'), ('order_ready', 'Order ready')], max_length=32)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=16)),
                ('destination', models.CharField(help_text='The number or address it was sent to.', max_length=200)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=16)),
                ('error', models.TextField(blank=True, default='', help_text='Why it failed, when it did. Empty on success.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reservation__isnull', False)), fields=('kind', 'reservation'), name='one_notification_per_kind_per_reservation'), models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('kind', 'order'), name='one_notification_per_kind_per_order'), models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', True), ('reservation__isnull', False)), models.Q(('order__isnull', False), ('reservation__isnull', True)), _connector='OR'), name='notification_is_about_exactly_one_thing')],
            },
        ),
    ]
