"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from decimal import Decimal
from pathlib import Path

from decouple import AutoConfig, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Look for a .env starting at backend/ and walking up to the repo root, so the
# file can live in either place.
config = AutoConfig(search_path=BASE_DIR)

# Which environment are we in? "local" (SQLite, zero setup) or "production"
# (PostgreSQL, DB_* variables required). See DATABASES below.
DJANGO_ENV = config('DJANGO_ENV', default='local')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # Local
    'establishments',
    'reservations',
    'payments',
    'orders',
    'accounts',
    'notifications',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must sit above CommonMiddleware so preflight OPTIONS requests get their
    # headers even when another middleware would short-circuit the response.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Reads Accept-Language and activates it for the request, so a French app
    # gets French error messages back. Must sit above CommonMiddleware.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# DJANGO_ENV=local (the default) needs no configuration at all: SQLite in
# backend/db.sqlite3. DJANGO_ENV=production reads the DB_* variables.

if DJANGO_ENV == 'production':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# English is the source language and the fallback; French is what most
# customers here actually read. A request with no Accept-Language gets
# English, which keeps every existing client working unchanged.
LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

# Reservations are booked in local Guinean time; datetimes are still stored in
# UTC (USE_TZ) and rendered in this zone.
TIME_ZONE = 'Africa/Conakry'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Uploaded files (establishment photos)
#
# Served by Django only when DEBUG is on — see config/urls.py. In production a
# web server or object store serves MEDIA_URL; Django must not.

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Largest photo a customer or merchant may upload. Phones here produce large
# files on poor connections, so the limit is enforced rather than hoped for.
MAX_PHOTO_UPLOAD_BYTES = config(
    'MAX_PHOTO_UPLOAD_BYTES', default=5 * 1024 * 1024, cast=int
)
ALLOWED_PHOTO_EXTENSIONS = ['jpg', 'jpeg', 'png', 'webp']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Token first: it is what the Flutter merchant app uses. Session auth
        # stays for the browsable API and /admin/.
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Per-view permissions decide what is public; see api/views.py. There is no
    # customer/merchant user model yet, so "authenticated" currently means an
    # admin logged in through /admin/ or the browsable API.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # Ceilings on the paths anyone can reach without signing in. Applied per
    # view rather than globally: a blanket rate needs real traffic to size,
    # and guessing one now risks throttling the first pilot. See
    # api/throttling.py for why each of these is keyed the way it is.
    'DEFAULT_THROTTLE_RATES': {
        'login_ip': '10/min',
        'login_username': '5/min',
        'register': '5/hour',
        'password_reset': '5/hour',
        'password_reset_identifier': '3/hour',
        'booking_ip': '30/hour',
        'booking_phone': '5/hour',
    },
}

# Off during tests: turning it on for the suite would mean every test that
# signs in twice fighting a counter that outlives it. The tests that actually
# care about throttling switch it back on explicitly.
THROTTLING_ENABLED = config(
    'THROTTLING_ENABLED', default='test' not in sys.argv, cast=bool
)


# CORS
#
# Only the Flutter *web* build needs this; Android and iOS are not subject to
# the browser's same-origin policy. `flutter run -d chrome` serves the app from
# a fresh random localhost port every run, so pinning an allowlist locally
# would mean editing this file constantly — hence allow-all in development
# only. Production reads an explicit list and fails closed if it is unset.

if DJANGO_ENV == 'production':
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())
else:
    CORS_ALLOW_ALL_ORIGINS = True

# Token auth travels in the Authorization header, not a cookie, so the browser
# never needs to send credentials cross-origin.
CORS_ALLOW_CREDENTIALS = False


# Booking rules
#
# Reservation has no duration field: every booking is assumed to run for
# RESERVATION_DURATION_MINUTES, which is what makes two bookings on one space
# "overlap". Availability is offered on a fixed grid inside a fixed daily
# window because Establishment.opening_hours is still free text and cannot be
# parsed — once it becomes structured, these three become per-establishment.

RESERVATION_DURATION_MINUTES = 120

# Payments
#
# Every provider currently resolves to the mock, which always succeeds. Real
# Orange Money / MTN adapters land behind the same interface, so switching one
# on is a change here rather than in the reservation flow.

PAYMENT_PROVIDERS = {
    'orange_money': 'payments.providers.MockPaymentProvider',
    'mtn_money': 'payments.providers.MockPaymentProvider',
}

# What a mobile money booking pays up front, in Guinean francs. Global for now;
# per-establishment pricing is a product decision, not a client-supplied value.
RESERVATION_DEPOSIT_AMOUNT = Decimal(
    config('RESERVATION_DEPOSIT_AMOUNT', default='50000')
)
AVAILABILITY_SLOT_MINUTES = 30

# How long a table is held for someone who has not arrived, per kind of venue.
# A lounge table is not lost at minute 16; a restaurant table held through a
# dinner service costs more in refused walk-ins than the deposit protects.
# Read only through reservations.no_show.no_show_window(), and captured on a
# booking when it is taken — never re-read live once the booking exists.
NO_SHOW_WINDOW_MINUTES = {
    'restaurant': config('NO_SHOW_WINDOW_RESTAURANT', default=30, cast=int),
    'lounge': config('NO_SHOW_WINDOW_LOUNGE', default=90, cast=int),
}
AVAILABILITY_WINDOW_START = '12:00'
AVAILABILITY_WINDOW_END = '23:00'


# --- Notifications --------------------------------------------------------
# Same shape as PAYMENT_PROVIDERS: swapping the console stub for a real SMS
# aggregator is a settings change, not a code change.
NOTIFIERS = {
    'sms': config(
        'SMS_NOTIFIER',
        default='accounts.notifications.ConsoleSmsNotifier',
    ),
    'email': config(
        'EMAIL_NOTIFIER',
        default='accounts.notifications.EmailNotifier',
    ),
}

# Console in development, so a reset code is readable in the terminal without
# anything actually leaving the machine.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@sylibooking.gn')


# --- Task queue -----------------------------------------------------------
# Work that is not a request: reminders, the no-show sweep, payment polling.
# Introduced empty on purpose — see config/celery.py.

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='')

# Run tasks in-process during tests rather than needing a broker: the suite
# tests what a task *does*, and a queue in the middle of that only adds a way
# for it to be flaky. The tests that care about queueing say so explicitly.
CELERY_TASK_ALWAYS_EAGER = config(
    'CELERY_TASK_ALWAYS_EAGER', default=False, cast=bool
)
# Eager mode swallows exceptions by default, which would let a broken task
# pass its own test.
CELERY_TASK_EAGER_PROPAGATES = True

CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE

# A worker that never gives up holds a slot for ever. Nothing here is so
# important that it should outlive the shift it belongs to.
CELERY_TASK_TIME_LIMIT = 300
CELERY_TASK_SOFT_TIME_LIMIT = 240

# Losing a queued reminder because a worker restarted is worse than sending
# one twice — and every task here is written to be safe to run twice.
CELERY_TASK_ACKS_LATE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Fail fast when the broker is unreachable rather than retrying inside the
# request that is trying to queue. Callers already treat "could not queue" as
# survivable — losing the work, not the booking — and that promise is worth
# nothing if making it takes ten seconds.
CELERY_BROKER_CONNECTION_RETRY = False
CELERY_BROKER_CONNECTION_MAX_RETRIES = 0
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_connect_timeout': 2,
    'socket_timeout': 2,
}

# What runs without anyone asking. Both are cheap and both are safe to run
# repeatedly, which is what lets them run this often.
CELERY_BEAT_SCHEDULE = {
    'queue-due-reminders': {
        'task': 'notifications.tasks.queue_due_reminders',
        'schedule': 300.0,
    },
    'sweep-no-shows': {
        'task': 'notifications.tasks.sweep_no_shows',
        'schedule': 600.0,
    },
    # Often, because the task itself decides which payments are actually due
    # — a tight beat with a decaying per-payment interval chases a fresh
    # payment hard without hammering the provider for a stale one.
    'poll-pending-payments': {
        'task': 'notifications.tasks.poll_pending_payments',
        'schedule': 30.0,
    },
}


# --- Reminders ------------------------------------------------------------

#: How long before a booking the customer is reminded.
REMINDER_LEAD_HOURS = config('REMINDER_LEAD_HOURS', default=3, cast=int)

#: Hours in which a reminder waits for morning instead of ringing a phone.
#: A reminder that wakes somebody is worse than no reminder at all.
REMINDER_QUIET_START = config('REMINDER_QUIET_START', default='22:00')
REMINDER_QUIET_END = config('REMINDER_QUIET_END', default='07:00')

#: How long a payment may sit pending before it is written off. Nobody
#: approves a mobile money prompt half an hour later.
PAYMENT_ABANDON_AFTER_MINUTES = config(
    'PAYMENT_ABANDON_AFTER_MINUTES', default=30, cast=int
)
