"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
import sys
from decimal import Decimal
from pathlib import Path

from decouple import AutoConfig, Csv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Look for a .env starting at backend/ and walking up to the repo root, so the
# file can live in either place.
config = AutoConfig(search_path=BASE_DIR)

# Which environment are we in? "local" (SQLite, zero setup) or "production"
# (PostgreSQL, DB_* variables required). See DATABASES below.
DJANGO_ENV = config('DJANGO_ENV', default='local')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# The platform's own hostnames, added without anybody having to remember them.
#
# Railway injects the domain it routes to, and — the part that catches people —
# sends its health check with `Host: healthcheck.railway.app`. Django answers a
# host it does not recognise with 400, so a service that is working perfectly
# fails its health check, gets restarted, and fails again. The logs say
# "Invalid HTTP_HOST header", which reads like an attack rather than the
# platform doing its job.
#
# Appended rather than replacing ALLOWED_HOSTS: a custom domain still has to be
# listed deliberately.
_platform_hosts = [
    config('RAILWAY_PUBLIC_DOMAIN', default=''),
    config('RAILWAY_PRIVATE_DOMAIN', default=''),
    'healthcheck.railway.app',
]

# On Railway, trust the platform's own domains as a family rather than by
# name.
#
# RAILWAY_PUBLIC_DOMAIN is documented but is not always in the process
# environment — notably when a domain is generated after the container
# started. The result is a service whose health check passes (that host is
# named above) and whose public domain answers 400 to every request, which
# reads as a broken deploy rather than a missing variable.
#
# The leading dot is Django's subdomain wildcard, so this covers
# <anything>.up.railway.app. What it gives up is host-header pinning against
# other Railway subdomains, which is worth having only if a forged Host can
# reach something — and it cannot here: password resets send a code rather
# than a link, so no email or SMS is built from the request's host.
#
# A custom domain still has to be listed in ALLOWED_HOSTS deliberately.
if config('RAILWAY_ENVIRONMENT', default='') or config(
    'RAILWAY_PROJECT_ID', default=''
):
    _platform_hosts.append('.railway.app')

for _platform_host in _platform_hosts:
    if _platform_host and _platform_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_platform_host)

# CSRF wants the scheme as well, and only for a domain a browser will use.
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
if _railway_domain := config('RAILWAY_PUBLIC_DOMAIN', default=''):
    _railway_origin = f'https://{_railway_domain}'
    if _railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_railway_origin)

# And the same family, for the same reason. Without this /admin/ presents a
# login form and then refuses the POST with "CSRF verification failed",
# which is the next thing somebody meets after the 400 above is fixed.
if config('RAILWAY_ENVIRONMENT', default='') or config(
    'RAILWAY_PROJECT_ID', default=''
):
    if 'https://*.railway.app' not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append('https://*.railway.app')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # Local
    'establishments',
    'reservations',
    'payments',
    'orders',
    'accounts',
    'notifications',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the collected static files — the admin's CSS and the browsable
    # API's — without a separate web server in front. There is no public
    # website here, so a whole nginx to serve a few hundred kilobytes of
    # admin assets would be a second thing to deploy and keep patched.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Must sit above CommonMiddleware so preflight OPTIONS requests get their
    # headers even when another middleware would short-circuit the response.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Reads Accept-Language and activates it for the request, so a French app
    # gets French error messages back. Must sit above CommonMiddleware.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# DJANGO_ENV=local (the default) needs no configuration at all: SQLite in
# backend/db.sqlite3. DJANGO_ENV=production reads DATABASE_URL if the host
# provides one, and the discrete DB_* variables otherwise.


def _database_from_url(url):
    """Parse the single connection string managed hosts hand out.

    Render, Railway and Fly all inject one DATABASE_URL rather than five
    variables, and it is generated — nobody types it, so nobody can split it
    into DB_NAME and friends without a step that will eventually be skipped.

    Hand-parsed rather than adding dj-database-url: it is a URL, the stdlib
    parses URLs, and a dependency whose whole job is six lines is a
    dependency to keep updated forever.
    """
    from urllib.parse import unquote, urlparse

    parsed = urlparse(url)
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': parsed.path.lstrip('/'),
        'USER': unquote(parsed.username or ''),
        # Unquoted: a generated password routinely contains characters that
        # have to be percent-encoded in a URL, and passing them through
        # still encoded is an authentication failure that reads like a wrong
        # password.
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or 'localhost',
        'PORT': str(parsed.port or 5432),
        # Managed Postgres is reached over the network and expects TLS.
        'OPTIONS': {'sslmode': config('DB_SSLMODE', default='require')},
        # One connection reused for a minute rather than a fresh one per
        # request. These hosts cap connections tightly and Celery holds its
        # own alongside the web workers.
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
    }


if DJANGO_ENV == 'production':
    _database_url = config('DATABASE_URL', default='')
    if _database_url:
        DATABASES = {'default': _database_from_url(_database_url)}
    else:
        # The five-variable form, for hosts that do not hand out a URL.
        #
        # Defaults rather than required, so a missing database is reported by
        # `check --deploy` naming DATABASE_URL — the variable somebody
        # actually sets — instead of raising about DB_NAME, which on Railway,
        # Render and Fly nobody has ever heard of. See config/checks.py.
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': config('DB_NAME', default=''),
                'USER': config('DB_USER', default=''),
                'PASSWORD': config('DB_PASSWORD', default=''),
                'HOST': config('DB_HOST', default='localhost'),
                'PORT': config('DB_PORT', default='5432'),
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# English is the source language and the fallback; French is what most
# customers here actually read. A request with no Accept-Language gets
# English, which keeps every existing client working unchanged.
LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

# Reservations are booked in local Guinean time; datetimes are still stored in
# UTC (USE_TZ) and rendered in this zone.
TIME_ZONE = 'Africa/Conakry'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
#: Where collectstatic writes. Baked into the image at build time rather than
#: collected at boot — see the Dockerfile.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded files (establishment photos)
#
# Served by Django only when DEBUG is on — see config/urls.py. In production a
# web server or object store serves MEDIA_URL; Django must not.

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Photos go to object storage in production, and have to.
#
# backend/media/ is inside the container: a redeploy replaces the container,
# and every photo a merchant uploaded goes with it. That is not a performance
# consideration, it is data loss on an ordinary Tuesday deploy — and the
# people who lose it are venues who spent an evening photographing their room.
#
# Any S3-compatible bucket. Written that way on purpose: the endpoint is a
# setting, so a regional provider can be used instead of AWS if that is what
# is actually payable from Guinea.
USE_S3_MEDIA = config('USE_S3_MEDIA', default=False, cast=bool)

# Static files and media files are decided independently, and that
# separation is load-bearing.
#
# They used to be one block: turning USE_S3_MEDIA on also switched static
# files to the manifest backend. The image collects static at build time with
# media storage off, so no manifest was ever written — and the first deploy
# with R2 enabled answered 500 to every HTML page, `Missing staticfiles
# manifest entry`, while the JSON API carried on working. A photo storage
# setting has no business deciding how CSS is served.
#
# The manifest backend is now unconditional, so the collect that happens in
# the Dockerfile always produces what the runtime always expects. In
# development DEBUG serves static through the finders and the manifest is
# never consulted.
_media_storage = {
    'BACKEND': 'django.core.files.storage.FileSystemStorage',
}

if USE_S3_MEDIA:
    _media_storage = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': config('AWS_STORAGE_BUCKET_NAME'),
            # R2 wants 'auto'; AWS wants a real region.
            'region_name': config('AWS_S3_REGION_NAME', default='auto'),
            # Blank for AWS itself; set for anyone else.
            'endpoint_url': config('AWS_S3_ENDPOINT_URL', default='') or None,
            'access_key': config('AWS_ACCESS_KEY_ID', default=''),
            'secret_key': config('AWS_SECRET_ACCESS_KEY', default=''),
            # No ACL. S3 has per-object ACLs and Cloudflare R2 does not — it
            # rejects the header outright, so asking for 'public-read' fails
            # every upload rather than making anything public. On R2 a bucket
            # is served publicly by attaching a domain to it, which is what
            # the custom domain below is for; on S3 use a bucket policy.
            'default_acl': None,
            # Unsigned URLs. Photos are shown to anyone browsing a venue, and
            # a signed URL would expire in the middle of a gallery.
            'querystring_auth': False,
            # The public hostname in front of the bucket. Without it
            # django-storages builds URLs against the S3 API endpoint, which
            # on R2 is not publicly readable — every photo would 401 while
            # looking perfectly configured.
            'custom_domain': config('MEDIA_CUSTOM_DOMAIN', default='') or None,
            # A photo never changes once uploaded — the filename carries a
            # uuid — so it can be cached hard. On the connections this market
            # runs on, that is the difference between a venue's gallery
            # loading and not.
            'object_parameters': {'CacheControl': 'max-age=86400'},
            # Never silently overwrite: two venues uploading terrasse.jpg must
            # not become one photo shown to both.
            'file_overwrite': False,
        },
    }

STORAGES = {
    'default': _media_storage,
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Largest photo a customer or merchant may upload. Phones here produce large
# files on poor connections, so the limit is enforced rather than hoped for.
MAX_PHOTO_UPLOAD_BYTES = config(
    'MAX_PHOTO_UPLOAD_BYTES', default=5 * 1024 * 1024, cast=int
)
ALLOWED_PHOTO_EXTENSIONS = ['jpg', 'jpeg', 'png', 'webp']

# How many photos one venue's gallery may take in a day, from everyone
# combined. A size cap alone bounds each file and nothing else: a hundred
# admissible 5 MB uploads is still half a gigabyte of disk and a gallery
# nobody can scroll. Counted per venue rather than per uploader because it is
# the venue's gallery that suffers, and a customer with a reference is not the
# only one who can post to it.
MAX_PHOTOS_PER_VENUE_PER_DAY = config(
    'MAX_PHOTOS_PER_VENUE_PER_DAY', default=40, cast=int
)

# The floor a password-reset request answers no faster than.
#
# The message is already the same whether or not the identifier exists. The
# work behind it is not: a hit issues a code, writes a row and hands it to a
# notifier, and a miss returns after one query. That difference is readable
# from outside as a yes/no on whether an account exists, and it gets worse,
# not better, once the notifier is a real SMS gateway making a network call.
# So both answers wait out the same floor. Affordable because this endpoint
# is already capped at a handful of requests an hour.
PASSWORD_RESET_MIN_SECONDS = config(
    'PASSWORD_RESET_MIN_SECONDS', default=0.25, cast=float
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Token first: it is what the Flutter merchant app uses. Session auth
        # stays for the browsable API and /admin/.
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Per-view permissions decide what is public; see api/views.py. There is no
    # customer/merchant user model yet, so "authenticated" currently means an
    # admin logged in through /admin/ or the browsable API.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # A floor under the whole API, so a route added next month is covered by
    # having been written rather than by somebody remembering to cover it.
    # Views that name their own throttles replace these, which is the order
    # wanted: the tighter, purpose-built limit wins where there is one.
    'DEFAULT_THROTTLE_CLASSES': [
        'api.throttling.AnonSurfaceThrottle',
        'api.throttling.UserSurfaceThrottle',
    ],
    # See api/throttling.py for why each of these is keyed the way it is.
    #
    # Every rate below now carries either a measurement or an argument, and
    # the two are labelled differently on purpose. Where it says *measured*,
    # the number came from driving the API the way the apps drive it and
    # counting; where it says *argued*, there is no traffic to measure and the
    # figure is reasoning about what the endpoint costs when abused.
    #
    # The measuring corrected an assumption worth recording: the surface rates
    # were described as "loose enough that no honest use should ever meet
    # them". They were not. Painting one browse list costs 22 requests,
    # because the list carries no cover photo and the app fetches one per
    # venue — so four customers on one café connection in the same minute came
    # within a few requests of a ceiling meant for abusers.
    #
    # Loosening a limit is not the direction anybody expects to move a
    # throttle, which is exactly why it needs the number written next to it.
    'DEFAULT_THROTTLE_RATES': {
        # Measured: 22 requests to paint one browse list (1 list + 20 covers +
        # detail). At 90/min a shared connection ran out at four sessions.
        # 180 buys eight, which covers a cybercafé; the real fix is to stop
        # asking twenty times, and that is an API change, not a rate.
        'anon_surface': '180/min',
        # Measured: a merchant desk load is up to 25 requests — reservations
        # paginate and `allReservations` walks up to 20 pages — plus a poll
        # every 60s. A merchant working quickly through a Friday evening can
        # reach ~100/min. Left where it is: 240 is about twice the worst
        # honest minute, and the cost of being wrong is a merchant locked out
        # of their own desk mid-service.
        'user_surface': '240/min',
        # Measured: 6 browse-scope requests per session, so 300/hour is 50
        # sessions from one address. Left alone — that is generous for a
        # person and mean enough to make scraping the catalogue tedious,
        # which is all this was ever meant to do.
        'browse': '300/hour',
        # Argued: a real person mistypes a password two or three times, not
        # ten. Both keys stay because they answer different attacks — the IP
        # one stops a spray, the username one stops a rotation.
        'login_ip': '10/min',
        'login_username': '5/min',
        # Argued: signing up is a once-ever act. Five an hour from one address
        # is already far past a household sharing a phone, and tightening
        # further would start refusing families rather than abusers.
        'register': '5/hour',
        'password_reset': '5/hour',
        'password_reset_identifier': '3/hour',
        # Tightened, 30 -> 15. Argued: even a busy shared connection books a
        # handful of tables an hour; thirty was a number nobody had reasoned
        # about. Fifteen still leaves several times honest peak.
        'booking_ip': '15/hour',
        # Tightened, 5 -> 3, and the one that matters most.
        #
        # This is not about junk rows. Once a real gateway is attached, each
        # booking pushes a payment prompt to whatever number was typed — so
        # this rate is the ceiling on how often a stranger can make one
        # person's phone ring, billed to us. A real customer books that number
        # once, occasionally twice. Three is honest peak plus one, and every
        # unit above it is somebody else's evening.
        'booking_phone': '3/hour',
    },
}

# Off during tests: turning it on for the suite would mean every test that
# signs in twice fighting a counter that outlives it. The tests that actually
# care about throttling switch it back on explicitly.
THROTTLING_ENABLED = config(
    'THROTTLING_ENABLED', default='test' not in sys.argv, cast=bool
)


# CORS
#
# Only the Flutter *web* build needs this; Android and iOS are not subject to
# the browser's same-origin policy. `flutter run -d chrome` serves the app from
# a fresh random localhost port every run, so pinning an allowlist locally
# would mean editing this file constantly — hence allow-all in development
# only. Production reads an explicit list and fails closed if it is unset.

if DJANGO_ENV == 'production':
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())
else:
    CORS_ALLOW_ALL_ORIGINS = True

# Token auth travels in the Authorization header, not a cookie, so the browser
# never needs to send credentials cross-origin.
CORS_ALLOW_CREDENTIALS = False


# Booking rules
#
# Reservation has no duration field: every booking is assumed to run for
# RESERVATION_DURATION_MINUTES, which is what makes two bookings on one space
# "overlap". Availability is offered on a fixed grid inside a fixed daily
# window because Establishment.opening_hours is still free text and cannot be
# parsed — once it becomes structured, these three become per-establishment.

RESERVATION_DURATION_MINUTES = 120

# Payments
#
# Every provider currently resolves to the mock, which always succeeds. Real
# Orange Money / MTN adapters land behind the same interface, so switching one
# on is a change here rather than in the reservation flow.

# Which adapter serves which provider. Both default to the mock, so a machine
# with no credentials behaves exactly as it always has — switching one on is
# this setting and nothing else.
#
#   ORANGE_MONEY_ADAPTER=payments.orange.OrangeMoneyProvider
#   MTN_MONEY_ADAPTER=payments.mtn.MtnMoneyProvider
#
# See DEPLOYMENT.md for what has to exist before either is worth setting.
PAYMENT_PROVIDERS = {
    'orange_money': config(
        'ORANGE_MONEY_ADAPTER',
        default='payments.providers.MockPaymentProvider',
    ),
    'mtn_money': config(
        'MTN_MONEY_ADAPTER',
        default='payments.providers.MockPaymentProvider',
    ),
}

# --- Orange Money ---------------------------------------------------------
#
# Every URL is configurable because Orange's contract differs by country and
# by merchant agreement. The defaults are the published shape; check them
# against what Orange sends you rather than trusting them.
ORANGE_MONEY = {
    'client_id': config('ORANGE_CLIENT_ID', default=''),
    'client_secret': config('ORANGE_CLIENT_SECRET', default=''),
    'merchant_key': config('ORANGE_MERCHANT_KEY', default=''),
    'token_url': config(
        'ORANGE_TOKEN_URL', default='https://api.orange.com/oauth/v3/token'
    ),
    'payment_url': config(
        'ORANGE_PAYMENT_URL',
        default='https://api.orange.com/orange-money-webpay/dev/v1/webpayment',
    ),
    'status_url': config(
        'ORANGE_STATUS_URL',
        default=(
            'https://api.orange.com/orange-money-webpay/dev/v1/'
            'transactionstatus'
        ),
    ),
    'currency': config('ORANGE_CURRENCY', default='GNF'),
    'lang': config('ORANGE_LANG', default='fr'),
    'reference': config('ORANGE_REFERENCE', default='Sylibooking'),
    # Where Orange sends the customer, and us, when a payment ends.
    'return_url': config('ORANGE_RETURN_URL', default=''),
    'cancel_url': config('ORANGE_CANCEL_URL', default=''),
    'notif_url': config('ORANGE_NOTIF_URL', default=''),
}

#: The secret in the notification URL's path. Without it that endpoint is a
#: write surface anybody can find, so an unset value refuses every callback
#: rather than accepting every callback.
ORANGE_CALLBACK_SECRET = config('ORANGE_CALLBACK_SECRET', default='')

# --- MTN Mobile Money -----------------------------------------------------
MTN_MOMO = {
    'base_url': config(
        'MTN_BASE_URL', default='https://sandbox.momodeveloper.mtn.com'
    ),
    'api_user': config('MTN_API_USER', default=''),
    'api_key': config('MTN_API_KEY', default=''),
    'subscription_key': config('MTN_SUBSCRIPTION_KEY', default=''),
    # 'sandbox' until MTN issues the production environment string for
    # Guinea, which is part of your contract with them.
    'environment': config('MTN_ENVIRONMENT', default='sandbox'),
    'currency': config('MTN_CURRENCY', default='EUR'),
    'payer_message': config('MTN_PAYER_MESSAGE', default='Sylibooking'),
    'payee_note': config('MTN_PAYEE_NOTE', default='Sylibooking booking'),
    # Refunds are a different MTN product with its own key, so a venue can
    # collect long before disbursements are arranged.
    'disbursement_subscription_key': config(
        'MTN_DISBURSEMENT_SUBSCRIPTION_KEY', default=''
    ),
}

MTN_CALLBACK_SECRET = config('MTN_CALLBACK_SECRET', default='')

# What a mobile money booking pays up front, in Guinean francs. Global for now;
# per-establishment pricing is a product decision, not a client-supplied value.
RESERVATION_DEPOSIT_AMOUNT = Decimal(
    config('RESERVATION_DEPOSIT_AMOUNT', default='50000')
)
AVAILABILITY_SLOT_MINUTES = 30

# How long a table is held for someone who has not arrived, per kind of venue.
# A lounge table is not lost at minute 16; a restaurant table held through a
# dinner service costs more in refused walk-ins than the deposit protects.
# Read only through reservations.no_show.no_show_window(), and captured on a
# booking when it is taken — never re-read live once the booking exists.
NO_SHOW_WINDOW_MINUTES = {
    'restaurant': config('NO_SHOW_WINDOW_RESTAURANT', default=30, cast=int),
    'lounge': config('NO_SHOW_WINDOW_LOUNGE', default=90, cast=int),
}
AVAILABILITY_WINDOW_START = '12:00'
AVAILABILITY_WINDOW_END = '23:00'


# --- Notifications --------------------------------------------------------
def json_setting(name, default):
    """An environment variable that carries JSON.

    Parsed here so a malformed value fails at boot with the variable's name in
    the message, rather than at midnight inside a Celery task.
    """
    raw = config(name, default=default)
    if isinstance(raw, (dict, list)):
        return raw
    try:
        return json.loads(raw)
    except ValueError as error:
        raise ImproperlyConfigured(f'{name} is not valid JSON: {error}') from error


# Same shape as PAYMENT_PROVIDERS: swapping the console stub for a real SMS
# aggregator is a settings change, not a code change.
NOTIFIERS = {
    # accounts.gateways.HttpSmsNotifier once a gateway is arranged.
    'sms': config(
        'SMS_NOTIFIER',
        default='accounts.notifications.ConsoleSmsNotifier',
    ),
    'email': config(
        'EMAIL_NOTIFIER',
        default='accounts.notifications.EmailNotifier',
    ),
    # accounts.gateways.WhatsAppNotifier once a WhatsApp Business number and
    # an approved template exist.
    'whatsapp': config(
        'WHATSAPP_NOTIFIER',
        default='accounts.notifications.ConsoleSmsNotifier',
    ),
}

# --- SMS gateway ----------------------------------------------------------
#
# Deliberately vendor-neutral: which aggregator serves Guinea is a commercial
# decision, and they all offer the same HTTP shape. `payload` is a template —
# {to}, {text} and {sender} are substituted wherever they appear, at any depth
# — so a new vendor is environment variables rather than an adapter.
#
# DEPLOYMENT.md carries worked examples for Twilio and for a generic reseller.
SMS_GATEWAY = {
    'url': config('SMS_URL', default=''),
    'method': config('SMS_METHOD', default='POST'),
    # 'json' or 'form'. Older aggregators want form-encoded.
    'encoding': config('SMS_ENCODING', default='json'),
    'sender': config('SMS_SENDER', default='Sylibooking'),
    'username': config('SMS_USERNAME', default=''),
    'password': config('SMS_PASSWORD', default=''),
    'default_country_code': config('SMS_COUNTRY_CODE', default='224'),
    'headers': json_setting('SMS_HEADERS', default='{}'),
    'payload': json_setting(
        'SMS_PAYLOAD',
        default='{"to": "{to}", "from": "{sender}", "text": "{text}"}',
    ),
    # Some gateways answer 200 and put the refusal in the body. Where these
    # are set, the body is checked; where they are not, a 200 is believed.
    'success_path': config('SMS_SUCCESS_PATH', default=''),
    'success_value': config('SMS_SUCCESS_VALUE', default=''),
}

# --- WhatsApp (Meta Cloud API) --------------------------------------------
#
# Only templates, because a first message outside a 24-hour reply window has
# to be one. The template itself is approved in Meta's console, not here.
WHATSAPP = {
    'base_url': config(
        'WHATSAPP_BASE_URL', default='https://graph.facebook.com/v21.0'
    ),
    'phone_number_id': config('WHATSAPP_PHONE_NUMBER_ID', default=''),
    'token': config('WHATSAPP_TOKEN', default=''),
    'template': config('WHATSAPP_TEMPLATE', default=''),
    'language': config('WHATSAPP_LANGUAGE', default='fr'),
    'default_country_code': config('SMS_COUNTRY_CODE', default='224'),
}

# Console in development, so a reset code is readable in the terminal without
# anything actually leaving the machine.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@sylibooking.gn')


# --- Cache ----------------------------------------------------------------
#
# **Shared, not per-process, and that is load-bearing.** Django's default is
# an in-memory cache local to each worker, which quietly breaks two things the
# moment there is more than one worker:
#
#   * Throttle counters. Each worker would count separately, so a limit of
#     "5 an hour" becomes five an hour *per worker* — the ceiling silently
#     multiplies by however many processes are running.
#   * The Orange Money payment context. `pay_token` is written when a payment
#     starts and read when its status is checked, and those are different
#     requests that land on different workers. A status check that cannot find
#     it can never settle the payment, so the customer pays and the booking
#     stays pending.
#
# So production uses Redis — the same instance Celery brokers through, on a
# different database number so a `FLUSHDB` on one does not take the other.
# Local development keeps the in-process cache, where there is only ever one
# process and no Redis to install.

_redis_url = config('REDIS_URL', default=config('CELERY_BROKER_URL', default=''))

if DJANGO_ENV == 'production' and _redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
            'KEY_PREFIX': 'sylibooking',
        }
    }
else:
    # No Redis. In development that is correct; in production it is a
    # misconfiguration, and it is reported by a deployment check rather than
    # by raising here.
    #
    # Raising at import made every management command explode — including
    # `check --deploy`, whose entire job is to *tell* you about this. A
    # traceback in place of a checklist is worse than the thing it was
    # guarding against, and it hid the message inside forty lines of Django
    # internals.
    #
    # The runtime guard now lives where a server actually starts: the
    # entrypoint runs `check --deploy` before gunicorn, so a container with
    # this wrong still refuses to serve.
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'sylibooking-local',
        }
    }


# --- Task queue -----------------------------------------------------------
# Work that is not a request: reminders, the no-show sweep, payment polling.
# Introduced empty on purpose — see config/celery.py.

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='')

# Run tasks in-process during tests rather than needing a broker: the suite
# tests what a task *does*, and a queue in the middle of that only adds a way
# for it to be flaky. The tests that care about queueing say so explicitly.
CELERY_TASK_ALWAYS_EAGER = config(
    'CELERY_TASK_ALWAYS_EAGER', default=False, cast=bool
)
# Eager mode swallows exceptions by default, which would let a broken task
# pass its own test.
CELERY_TASK_EAGER_PROPAGATES = True

CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE

# A worker that never gives up holds a slot for ever. Nothing here is so
# important that it should outlive the shift it belongs to.
# How many processes a worker forks.
#
# Celery's default is the host's CPU count, and a container platform reports
# the underlying machine rather than your share of it — Railway booted this
# with `concurrency: 48 (prefork)`, which is 48 full copies of Django waiting
# for three small tasks a minute. On a container this size that is either an
# OOM kill under load or a memory bill for processes that are never busy.
#
# Two, for the same reason WEB_CONCURRENCY exists: the platform knows how big
# the container is and the default does not. Raise it when a task starts
# taking real time — the payment poller is 40ms and the reminders are an HTTP
# call each.
CELERY_WORKER_CONCURRENCY = config('CELERY_WORKER_CONCURRENCY', default=2, cast=int)

CELERY_TASK_TIME_LIMIT = 300
CELERY_TASK_SOFT_TIME_LIMIT = 240

# Losing a queued reminder because a worker restarted is worse than sending
# one twice — and every task here is written to be safe to run twice.
CELERY_TASK_ACKS_LATE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Fail fast when the broker is unreachable rather than retrying inside the
# request that is trying to queue. Callers already treat "could not queue" as
# survivable — losing the work, not the booking — and that promise is worth
# nothing if making it takes ten seconds.
CELERY_BROKER_CONNECTION_RETRY = False
CELERY_BROKER_CONNECTION_MAX_RETRIES = 0
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_connect_timeout': 2,
    'socket_timeout': 2,
}

# What runs without anyone asking. Both are cheap and both are safe to run
# repeatedly, which is what lets them run this often.
CELERY_BEAT_SCHEDULE = {
    'queue-due-reminders': {
        'task': 'notifications.tasks.queue_due_reminders',
        'schedule': 300.0,
    },
    'sweep-no-shows': {
        'task': 'notifications.tasks.sweep_no_shows',
        'schedule': 600.0,
    },
    # Often, because the task itself decides which payments are actually due
    # — a tight beat with a decaying per-payment interval chases a fresh
    # payment hard without hammering the provider for a stale one.
    'poll-pending-payments': {
        'task': 'notifications.tasks.poll_pending_payments',
        'schedule': 30.0,
    },
}


# --- Reminders ------------------------------------------------------------

#: How long before a booking the customer is reminded.
REMINDER_LEAD_HOURS = config('REMINDER_LEAD_HOURS', default=3, cast=int)

#: Hours in which a reminder waits for morning instead of ringing a phone.
#: A reminder that wakes somebody is worse than no reminder at all.
REMINDER_QUIET_START = config('REMINDER_QUIET_START', default='22:00')
REMINDER_QUIET_END = config('REMINDER_QUIET_END', default='07:00')

#: How long a payment may sit pending before it is written off. Nobody
#: approves a mobile money prompt half an hour later.
PAYMENT_ABANDON_AFTER_MINUTES = config(
    'PAYMENT_ABANDON_AFTER_MINUTES', default=30, cast=int
)


# --- Observability --------------------------------------------------------
#
# When something breaks in Conakry, the point is to find out from a dashboard
# rather than from a merchant on the phone.

#: JSON log lines in production, plain text where a person is reading them.
STRUCTURED_LOGGING = config(
    'STRUCTURED_LOGGING', default=DJANGO_ENV == 'production', cast=bool
)
LOG_LEVEL = config('LOG_LEVEL', default='DEBUG' if DEBUG else 'INFO')

from config.logging import logging_config  # noqa: E402

LOGGING = logging_config(structured=STRUCTURED_LOGGING, level=LOG_LEVEL)

#: Empty everywhere but production. See config/errors.py: with no DSN the
#: reporter writes to the log, which is a real destination rather than a
#: silent one.
SENTRY_DSN = config('SENTRY_DSN', default='')


# --- Production hardening -------------------------------------------------
#
# Only in production. Turning these on locally would mean a redirect to https
# on a development server that does not speak it, which reads as the app
# being broken.

if DJANGO_ENV == 'production':
    # TLS is terminated by the platform in front of this process, so Django
    # has to be told to believe the header rather than the socket — without
    # this it sees http, decides the request is insecure, and redirects
    # forever.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Off while running tests, the same way THROTTLING_ENABLED is, and for
    # the same reason: the test client speaks http, so a redirect turns every
    # single request into a 301 and the whole production suite tests nothing
    # but Django's ability to redirect. This is why the PostgreSQL job has
    # been red — 370 failures, all of them this.
    SECURE_SSL_REDIRECT = config(
        'SECURE_SSL_REDIRECT', default='test' not in sys.argv, cast=bool
    )

    # The health probes, exempt from that redirect.
    #
    # A platform's health checker reaches the container directly rather than
    # through the proxy that terminates TLS, so the request arrives as plain
    # http with no X-Forwarded-Proto to say otherwise. Django does exactly
    # what it was told and answers 301; the platform reads that as unhealthy,
    # restarts a perfectly good container, and does it again.
    #
    # Exempting only these two paths keeps the redirect everywhere it
    # matters. Nothing here is secret — one answers "the process is alive"
    # and the other names which dependency is not — and neither takes input,
    # so there is nothing for the plain-text hop to leak.
    #
    # Patterns are matched against the path with its leading slash stripped,
    # which is why there is none here.
    SECURE_REDIRECT_EXEMPT = [r'^api/health/']

    # Six months. Deliberately not preloaded: preload is close to
    # irreversible, and committing every future subdomain to https before
    # there is a domain at all is a decision made too early.
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=15552000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False

    # Django warns about the line above (security.W021), and the warning is
    # right in general and wrong here. Preloading is close to irreversible —
    # browsers ship the list — and it commits every future subdomain to https
    # before this project has a domain at all. Silenced rather than obeyed,
    # so the rest of the deployment checklist can fail the build.
    SILENCED_SYSTEM_CHECKS = ['security.W021']

    # The session cookie is only used by /admin/ and the browsable API — the
    # apps carry a token in a header — but /admin/ is the account that can
    # read every booking on the platform.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    # CSRF_TRUSTED_ORIGINS is set near ALLOWED_HOSTS, where the platform's
    # own domain is added to it. Re-reading the variable here would silently
    # drop that, which /admin/ would then refuse every login from.


#: How a push is actually sent. The console sender runs everywhere until a
#: Firebase project exists; swapping this is configuration, not a rewrite.
PUSH_SENDER = config(
    'PUSH_SENDER', default='notifications.push.ConsolePushSender'
)
