# Generated by Django 5.2.7 on 2026-07-31 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0008_theme_preset'),
        ('reservations', '0002_reservation_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unguessable handle the customer uses to follow their own order. Customers have no accounts, so this is what proves the order is theirs — the sequential id must not be used for that.', unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(help_text='How the counter reaches the customer when it is ready.', max_length=30)),
                ('pickup_time', models.DateTimeField(help_text='When the customer says they will collect. Stored in UTC.')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='placed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('establishment', models.ForeignKey(help_text='Where the food is cooked and collected.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='establishments.establishment')),
                ('reservation', models.ForeignKey(blank=True, help_text='The table booking this order belongs to, when there is one. Null for a standalone pickup. SET_NULL rather than CASCADE: a cancelled booking must not silently delete food the kitchen may already have started.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='reservations.reservation')),
            ],
            options={
                'ordering': ['pickup_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_at_order', models.DecimalField(decimal_places=2, help_text='Copied from MenuItem.price when the order is created, and never recalculated. A merchant raising a price this afternoon must not change what this morning owes.', max_digits=12)),
                ('menu_item', models.ForeignKey(help_text='PROTECT rather than CASCADE: deleting a dish from the menu must not erase the record of what somebody bought.', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='establishments.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['establishment', 'pickup_time'], name='orders_orde_establi_9091ad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
    ]
