# Generated by Django 5.2.7 on 2026-08-13 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unguessable handle the customer uses to follow their own order. An account is optional and most customers will not have one, so this is what proves the order is theirs — the sequential id must not be used for that.', unique=True),
        ),
    ]
