# Generated by Django 5.2.7 on 2026-07-26 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Name the booking is under.', max_length=200)),
                ('customer_phone', models.CharField(help_text='Phone number for confirmation/reminder, e.g. "+224 620 00 00 00".', max_length=30)),
                ('datetime', models.DateTimeField(help_text='Start of the reservation.')),
                ('party_size', models.PositiveSmallIntegerField(help_text='Number of guests expected.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Merchant confirms or cancels; completed is set after the visit.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(help_text='The table or room being held.', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='establishments.space')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
