# Generated by Django 5.2.7 on 2026-08-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='When the merchant marked the guests as arrived.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_show_after_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The grace period this booking was taken under, copied from the venue when it was made. Deliberately not read live: the customer is told this figure before they book, and shortening the venue’s window afterwards must not retroactively make them a no-show — or forfeit a deposit taken under longer terms.', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'Missed')], default='pending', help_text='Merchant confirms or cancels; completed is set when the guests arrive, and missed when the grace period passes without them.', max_length=20),
        ),
    ]
