# Generated by Django 5.2.7 on 2026-08-13 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_arrived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reference',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unguessable handle the customer uses to view or cancel their own booking. An account is optional and most customers will not have one, so this is what proves the booking is theirs — the sequential id must not be used for that.', unique=True),
        ),
    ]
