# Generated by Django 5.2.7 on 2026-07-28 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_reservation_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('cash_on_arrival', 'Cash on arrival')], help_text='How the money is being collected.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Guinean francs. Set server-side from settings.RESERVATION_DEPOSIT_AMOUNT so a client cannot choose what it owes.', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Updated from the provider, never by the client.', max_length=20)),
                ('provider_reference', models.CharField(blank=True, help_text="The provider's own id for this transaction, used to poll it later. Null until initiate_payment returns.", max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(help_text='The booking this payment is for.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_reference'], name='payments_pa_provide_48cfd7_idx')],
            },
        ),
    ]
