# Generated by Django 5.2.7 on 2026-07-31 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        ('reservations', '0002_reservation_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The pickup order this payment is for, if it is for one.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='The booking this payment is for, if it is for a booking.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', True), ('reservation__isnull', False)), models.Q(('order__isnull', False), ('reservation__isnull', True)), _connector='OR'), name='payment_settles_exactly_one_thing'),
        ),
    ]
