# Generated by Django 5.2.7 on 2026-08-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_order_alter_payment_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='outcome',
            field=models.CharField(choices=[('none', 'Not settled yet'), ('offset', 'Taken off the bill'), ('forfeited', 'Kept for a no-show'), ('refunded', 'Refunded')], default='none', help_text='What became of the deposit once the booking ended: taken off the bill when the guests arrived, kept when they did not. Set by payments.services.settle_deposit, never by a client.', max_length=20),
        ),
    ]
