# Generated by Django 5.2.7 on 2026-08-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, help_text='When the provider was last asked about this payment. Drives the decaying poll interval — a payment opened a minute ago is worth asking about often, one opened twenty minutes ago is not.', null=True),
        ),
    ]
