# Generated by Django 5.2.7 on 2026-07-26 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Public name of the establishment, e.g. "Le Petit Baobab".', max_length=200)),
                ('type', models.CharField(choices=[('lounge', 'Lounge'), ('restaurant', 'Restaurant')], help_text='Lounge or restaurant. Both take reservations the same way.', max_length=20)),
                ('city', models.CharField(help_text='City the establishment operates in, e.g. "Conakry", "Labé".', max_length=100)),
                ('address', models.TextField(help_text='Street address or directions as a customer would need them.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Decimal degrees, e.g. 9.641185. Optional.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Decimal degrees, e.g. -13.578401. Optional.', max_digits=9, null=True)),
                ('opening_hours', models.TextField(blank=True, help_text='Free text for now, e.g. "Mon-Thu 18:00-02:00, Fri-Sun 16:00-04:00". Becomes structured data once availability logic needs to parse it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label the staff use, e.g. "Table 4", "VIP Room 1".', max_length=100)),
                ('type', models.CharField(choices=[('table', 'Table'), ('vip_room', 'VIP room'), ('terrace', 'Terrace')], default='table', help_text='What kind of space this is.', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(help_text='Maximum number of guests this space seats.')),
                ('establishment', models.ForeignKey(help_text='The establishment this space belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='establishments.establishment')),
            ],
            options={
                'ordering': ['establishment', 'name'],
                'constraints': [models.UniqueConstraint(fields=('establishment', 'name'), name='unique_space_name_per_establishment')],
            },
        ),
    ]
