# Generated by Django 5.2.7 on 2026-07-26 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='staff',
            field=models.ManyToManyField(blank=True, help_text="Users who may see and manage this establishment's reservations in the merchant app.", related_name='establishments', to=settings.AUTH_USER_MODEL),
        ),
    ]
