# Generated by Django 5.2.7 on 2026-07-28 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_establishment_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Free-text note shown under the structured hours, e.g. "Kitchen closes at 23:00". Superseded by the OpeningHours rows for anything the apps compute from.'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, help_text='One line at most; this is a browsing screen.', max_length=300)),
                ('category', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('chicha_flavor', 'Chicha flavour')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='In Guinean francs.', max_digits=12)),
                ('is_available', models.BooleanField(default=True, help_text='Unavailable items are hidden from customers, not deleted.')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='establishments.establishment')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text="0 is Monday, matching Python's datetime.weekday().")),
                ('is_closed', models.BooleanField(default=False, help_text='Closed all day. Opens/closes are ignored when set.')),
                ('opens', models.TimeField(blank=True, help_text='Ignored when closed all day.', null=True)),
                ('closes', models.TimeField(blank=True, help_text='Earlier than opens means the venue runs past midnight, e.g. 18:00 to 02:00.', null=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='establishments.establishment')),
            ],
            options={
                'verbose_name_plural': 'opening hours',
                'ordering': ['establishment', 'day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('establishment', 'day_of_week'), name='unique_hours_per_day_per_establishment')],
            },
        ),
    ]
