# Generated by Django 5.2.7 on 2026-07-28 22:11

import django.core.validators
import django.db.models.deletion
import establishments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0003_alter_establishment_opening_hours_menuitem_and_more'),
        ('reservations', '0002_reservation_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by_role', models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant')], help_text="Merchant photos are the venue's own; customer photos are not.", max_length=20)),
                ('image', models.ImageField(upload_to=establishments.models.photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden photos are excluded from every customer-facing response. Moderation only.')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='establishments.establishment')),
                ('reservation', models.ForeignKey(blank=True, help_text="The booking a customer uploaded this from. Null for the venue's own photos.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional — a rating on its own is a valid review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden reviews are excluded from every customer-facing response and from the average rating. Moderation only; never exposed.')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='establishments.establishment')),
                ('reservation', models.OneToOneField(help_text='The visit being reviewed. One review per booking.', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5')],
            },
        ),
    ]
