# Generated by Django 5.2.7 on 2026-07-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0004_photo_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
