# Generated by Django 5.2.7 on 2026-07-29 02:14

import django.core.validators
import establishments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0006_merchant_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional. Most items will not have one, especially at first.', null=True, upload_to=establishments.models.menu_item_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
