# Generated by Django 5.2.7 on 2026-07-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0007_menu_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='theme_preset',
            field=models.CharField(choices=[('ember', 'Ember'), ('palm_night', 'Palm Night'), ('harmattan', 'Harmattan'), ('bissap', 'Bissap'), ('indigo_soir', 'Indigo Soir')], default='ember', help_text='Which curated branding preset this venue uses. The key is the only thing stored — colours and fonts live in the shared design file, so a merchant cannot pick something unreadable.', max_length=30),
        ),
    ]
