# Generated by Django 5.2.7 on 2026-08-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0009_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this space can still be booked. Taking a table out of service deactivates it rather than deleting it: its past bookings are part of the venue’s history, and the reservation row protects it from deletion anyway.'),
        ),
    ]
