# Generated by Django 5.2.7 on 2026-08-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0010_space_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='flagged_at',
            field=models.DateTimeField(blank=True, help_text='When the venue asked for this review to be looked at. Flagging is all a merchant may do: a venue that can hide its own bad reviews has a ratings system worth nothing, and the trust cost lands on the platform rather than the venue. Only an admin sets is_hidden.', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='flagged_reason',
            field=models.TextField(blank=True, default='', help_text='Why the venue says it should be looked at.'),
        ),
    ]
