# Generated by Django 5.2.7 on 2026-08-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0011_review_flagged_at_review_flagged_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Shown on the customer app's dishes feed, across all venues. A venue puts its best few here; it is a shop window, not a menu."),
        ),
    ]
