# Generated by Django 5.2.7 on 2026-08-13 14:01

import establishments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0012_menuitem_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='detail',
            field=models.ImageField(blank=True, help_text='Detail-sized copy, generated. Empty means use the original.', null=True, upload_to=establishments.models.derivative_upload_path),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Card-sized copy, generated. Empty means use the original.', null=True, upload_to=establishments.models.derivative_upload_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='detail',
            field=models.ImageField(blank=True, help_text='Detail-sized copy, generated. Empty means use the original.', null=True, upload_to=establishments.models.derivative_upload_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Card-sized copy, generated. Empty means use the original.', null=True, upload_to=establishments.models.derivative_upload_path),
        ),
    ]
